# Generated by Django 2.2.24 on 2021-08-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
